# Generated by Django 5.1.7 on 2025-04-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.DeleteModel(
            name='FoodTypeCategory',
        ),
        migrations.DeleteModel(
            name='SpeciesCategory',
        ),
    ]
