# Generated by Django 5.1.7 on 2025-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0006_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images/'),
        ),
    ]
